version: '3.3'
services:
  canary-frontend:
    restart: always
    image: 127.0.0.1:7000/canary-frontend:latest
    env_file:
      - .env.staging.docker
    environment:
      - REACT_APP_API_URL=https://api-staging.projectcanary.io/api/v1
    build:
      dockerfile: dockerfiles/nginx/Dockerfilestaging
      context: .
    networks:
      - frontendnet
    ports:
      - 5555:8090
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 15
        window: 120s
networks:
  frontendnet:
volumes:
 canary-frontend:
